name: Build

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "release-bot@groww.in"
      - run: git config --global user.name "github-bot"
      - run: npm install
      - run: npm run build

      - name: Deploy the documents on github pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run push-doc -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: npm run pushTags
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
